// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GQRunway struct {
	ID            string     `json:"id"`
	Designator    string     `json:"designator"`
	Contamination []*GQTuple `json:"contamination"`
	Coverage      []*GQTuple `json:"coverage"`
	Depth         []*GQTuple `json:"depth"`
	LooseSand     *bool      `json:"looseSand"`
	LatestVersion *int       `json:"latestVersion"`
}

type GQTuple struct {
	Key   string `json:"key"`
	Value int    `json:"value"`
}

type NewRunway struct {
	Designator string `json:"designator"`
}
